name: Bug Report
description: Report any bugs or issues.
title: '[Bug]: Describe the issue briefly'
labels: ['Type: Bug']
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Answers checklist.
      description: Before submitting a new issue, please follow the checklist and try to find the answer.
      options:
        - label: I have read the documentation, but the issue is not addressed there.
          required: true
        - label: I have updated my ameba-rtos-z2 branch to the latest version and confirmed that the issue is still present.
          required: true
        - label: I have searched the issue tracker([closed](https://github.com/Ameba-AIoT/ameba-rtos-z2/issues?q=is%3Aissue+label%3AType%3A+Bug+is%3Aclosed) and [existing](https://github.com/Ameba-AIoT/ameba-rtos-z2/issues?q=is%3Aissue+label%3AType%3A+Bug+is%3Aopen)) but did not find a similar issue.
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Ameba-rtos-z2 version.
      description: On which version does this issue occur? Indicate the commit ID.
      placeholder: 'ex. SHA-1: 778a36a48daacdfd67389bd739fc6e8f6d9f475a'
    validations:
      required: true
  - type: input
    id: chip
    attributes:
      label: Ameba-rtos-z2 chip.
      description: On which chip does your application run? Check the build project.
      placeholder: ex. amebaz2/amebaz2plus
    validations:
      required: true
  - type: textarea
    id: hardware
    attributes:
      label: External hardware.
      description: Any external hardware that Ameba board attached to? 
      placeholder: eg. third-party extension, plain module on breadboard, customized hardware... please attach a photo if necessary.
    validations:
      required: false
  - type: dropdown
    id: system
    attributes:
      label: Compile system used.
      description: On which OS does this issue occur?
      options:
        - Linux
        - Windows
      default: 0
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is the expected behavior?
      description: Please provide a clear and concise description of the expected behavior.
      placeholder: I expected it to...
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What is the actual behavior?
      description: Please describe actual behavior.
      placeholder: Instead it...
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Relevant code.
      description: Please provide sketch/code that can be used to reproduce the bug/issue.
      render: c
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce.
      description: 'How do you trigger this bug? Please provide a step-by-step explanation.'
      value: |
        1. Step
        2. Step
        3. Step
        ...
    validations:
      required: true 
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please provide all relevant log outputs. It should include the backtrace, as well as the reset source if it is a crash.
      render: plain
    validations:
      required: false 
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information.
      description: Do you have any additional information from your investigation?
      placeholder: ex. I tried on other chip/branch/version, and works fine.
    validations:
      required: false
